version: '3'

services:
   mongoumsdb:
        image: mongo
        container_name: "mongoUmsContainer"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null        
        ports:
            - 27017:27017

   dfc.ums.microservice:
    image: dfcumsmicroservice
    build:
      context: .
      dockerfile: DFC.UMS.Microservice/Dockerfile
    depends_on:
            - mongoumsdb
